In [28]:
import pandas as pd
from ast import literal_eval

df = pd.read_csv('./test_TM.csv')
df['zsl'].tolist()

["{'출연진': 23.35, '연기력': 38.82, '시나리오': 84.73, '연출': 29.65, '등장인물': 79.95}",
 "{'출연진': 49.1, '연기력': 77.89, '시나리오': 73.36, '연출': 75.86, '등장인물': 76.97}",
 "{'출연진': 88.7, '연기력': 49.12, '시나리오': 74.93, '연출': 65.49, '등장인물': 92.45}",
 "{'출연진': 49.84, '연기력': 37.84, '시나리오': 65.3, '연출': 38.72, '등장인물': 72.85}",
 "{'출연진': 49.19, '연기력': 45.26, '시나리오': 57.63, '연출': 60.29, '등장인물': 87.31}",
 "{'출연진': 27.85, '연기력': 70.34, '시나리오': 51.24, '연출': 42.23, '등장인물': 69.46}",
 "{'출연진': 37.19, '연기력': 14.69, '시나리오': 10.96, '연출': 22.88, '등장인물': 85.9}",
 "{'출연진': 21.36, '연기력': 74.3, '시나리오': 62.24, '연출': 69.91, '등장인물': 60.63}",
 "{'출연진': 47.87, '연기력': 50.16, '시나리오': 69.23, '연출': 69.64, '등장인물': 76.89}",
 "{'출연진': 64.81, '연기력': 78.07, '시나리오': 67.0, '연출': 55.05, '등장인물': 83.59}",
 "{'출연진': 47.74, '연기력': 58.18, '시나리오': 36.65, '연출': 63.76, '등장인물': 92.41}",
 "{'출연진': 32.81, '연기력': 61.8, '시나리오': 38.97, '연출': 49.87, '등장인물': 76.78}",
 "{'출연진': 47.92, '연기력': 45.25, '시나리오': 31.84, '연출': 66.99, '등장인물': 92.74}",
 "{'출연진': 42.14, '연기력': 33.41, '시나리오': 40.48, '연출': 24.83, '등장인물': 80.19}",
 "{'출연진': 72.31, '연기력': 28.71, '시나리오': 55.41, '연출': 57.48, '등장인물': 91.68}",
 "{'출연진': 45.06, '연기력': 46.1, '시나리오': 73.64, '연출': 74.85, '등장인물': 85.37}",
 "{'출연진': 51.74, '연기력': 30.01, '시나리오': 52.56, '연출': 41.52, '등장인물': 91.32}",
 "{'출연진': 41.74, '연기력': 38.62, '시나리오': 60.07, '연출': 42.04, '등장인물': 72.04}",
 "{'출연진': 56.44, '연기력': 45.16, '시나리오': 36.76, '연출': 79.01, '등장인물': 85.23}",
 "{'출연진': 17.98, '연기력': 22.53, '시나리오': 52.6, '연출': 51.11, '등장인물': 63.81}",
 "{'출연진': 73.36, '연기력': 48.9, '시나리오': 59.61, '연출': 32.37, '등장인물': 81.72}"]

In [32]:
container = []
for df_zsl in df['zsl'].tolist():
    dict_zsl= literal_eval(df_zsl)
    casting = dict_zsl['출연진']
    acting = dict_zsl['연기력']
    scenario = dict_zsl['시나리오']
    direction = dict_zsl['연출']
    character = dict_zsl['등장인물']
    context = [casting, acting, scenario, direction, character]
    container.append(context)
container

[[23.35, 38.82, 84.73, 29.65, 79.95],
 [49.1, 77.89, 73.36, 75.86, 76.97],
 [88.7, 49.12, 74.93, 65.49, 92.45],
 [49.84, 37.84, 65.3, 38.72, 72.85],
 [49.19, 45.26, 57.63, 60.29, 87.31],
 [27.85, 70.34, 51.24, 42.23, 69.46],
 [37.19, 14.69, 10.96, 22.88, 85.9],
 [21.36, 74.3, 62.24, 69.91, 60.63],
 [47.87, 50.16, 69.23, 69.64, 76.89],
 [64.81, 78.07, 67.0, 55.05, 83.59],
 [47.74, 58.18, 36.65, 63.76, 92.41],
 [32.81, 61.8, 38.97, 49.87, 76.78],
 [47.92, 45.25, 31.84, 66.99, 92.74],
 [42.14, 33.41, 40.48, 24.83, 80.19],
 [72.31, 28.71, 55.41, 57.48, 91.68],
 [45.06, 46.1, 73.64, 74.85, 85.37],
 [51.74, 30.01, 52.56, 41.52, 91.32],
 [41.74, 38.62, 60.07, 42.04, 72.04],
 [56.44, 45.16, 36.76, 79.01, 85.23],
 [17.98, 22.53, 52.6, 51.11, 63.81],
 [73.36, 48.9, 59.61, 32.37, 81.72]]

In [34]:
df_zsl = pd.DataFrame(container, columns=['출연진', '연기력', '시나리오', '연출', '등장인물'])

In [37]:
df_score = df['score']

In [41]:
df_preprocessed = pd.concat([df_zsl, df_score], axis=1)
df_preprocessed

      출연진    연기력   시나리오     연출   등장인물  score
0   23.35  38.82  84.73  29.65  79.95   4.78
1   49.10  77.89  73.36  75.86  76.97   4.16
2   88.70  49.12  74.93  65.49  92.45   2.02
3   49.84  37.84  65.30  38.72  72.85   3.89
4   49.19  45.26  57.63  60.29  87.31   3.66
5   27.85  70.34  51.24  42.23  69.46   4.87
6   37.19  14.69  10.96  22.88  85.90   4.74
7   21.36  74.30  62.24  69.91  60.63   1.80
8   47.87  50.16  69.23  69.64  76.89   3.85
9   64.81  78.07  67.00  55.05  83.59   4.69
10  47.74  58.18  36.65  63.76  92.41   4.39
11  32.81  61.80  38.97  49.87  76.78   4.80
12  47.92  45.25  31.84  66.99  92.74   4.64
13  42.14  33.41  40.48  24.83  80.19   4.99
14  72.31  28.71  55.41  57.48  91.68   4.96
15  45.06  46.10  73.64  74.85  85.37   3.44
16  51.74  30.01  52.56  41.52  91.32   3.84
17  41.74  38.62  60.07  42.04  72.04   1.75
18  56.44  45.16  36.76  79.01  85.23   4.36
19  17.98  22.53  52.60  51.11  63.81   1.25
20  73.36  48.90  59.61  32.37  81.72   5.01

In [42]:
df_preprocessed.to_csv('test_preprocessed.csv')